name: Semgrep

on:
  push:
    branches: ["main", "scpdpi"]

  pull_request:
    branches: ["main", "scpdpi"]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: PHP Security Scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep \
            --config=p/php \
            --sarif \
            --output=semgrep.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif